---
- block:
  - name: Get vault checksums
    uri:
      url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_SHA256SUMS"
      method: GET
      return_content: true
      status_code: 200
      validate_certs: false
    no_log: true
    register: _vault_checksums
    until: _vault_checksums.status == 200
    retries: 5
    run_once: true

  - name: Get checksum for {{ ansible_system }} {{ ansible_architecture }} architecture
    set_fact:
      vault_checksum: "{{ (_vault_checksums.content.split('\n') | select('search', ansible_system | lower + '_' + go_arch + '.zip') | list | first).split(' ')[0] }}"

  - name: Download vault to local folder
    get_url:
      url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
      dest: "/tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
      checksum: "sha256:{{ vault_checksum }}"
    register: _download_result
    until: _download_result is succeeded
    retries: 5
    delay: 2
    check_mode: false

  - name: Create vault tmp dir
    file:
      path: "/tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}"
      state: directory
      mode: 0755

  - name: Unpack vault
    unarchive:
      src: "/tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}.zip"
      dest: "/tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}"
      creates: "/tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}/vault"
    check_mode: false
  delegate_to: localhost
  become: false

- name: Ensure "/usr/local/bin" dir exists
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755
  become: yes

- name: Propagate vault binaries
  copy:
    src: "/tmp/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ go_arch }}/vault"
    dest: /usr/local/bin/vault
    mode: 0755
    owner: root
    group: root
  when: not ansible_check_mode